{% set version = "3.1.0" %}
{% set commit = "653b8ff129a9676d1bc69ee5231cf12f9aadd7e9" %}
{% set sha256 = "9d5a55c467253b19f7facdd6e1b3ca31ab7371bdc573b715e5e54033d668526a" %}

package:
  name: gudhi
  version: {{ version }}

source:
  url: https://github.com/GUDHI/gudhi-devel/archive/{{ commit }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # C++11 only supports vc14
  skip: true  # [win and py2k]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - setuptools
    - cython
    - boost-cpp {{ boost_version }}
    - eigen
    - cgal-cpp 5.0
    - mpfr
    - mpir
  run:
    - python
    - numpy
    - setuptools
    - boost-cpp {{ boost_version }}
    - cgal-cpp 5.0
    - mpfr
    - mpir

test:
  commands:
    - test -f ${PREFIX}/include/gudhi/Simplex_tree.h  # [unix]
    - if not exist %LIBRARY_INC%\gudhi\Simplex_tree.h exit 1  # [win]
    - conda inspect linkages $PKG_NAME  # [not win]
    - conda inspect objects $PKG_NAME  # [osx]
    - python -c "import gudhi; diag1 = [[2.7, 3.7], [9.6, 14.0], [34.2, 34.974], [3.0, float('Inf')]]; diag2 = [[2.8, 4.45], [9.5, 14.1], [3.2, float('Inf')]]; assert gudhi.bottleneck_distance(diag1, diag2) == 0.75"
about:
  home: http://gudhi.gforge.inria.fr/
  license: MIT/GPL3
  license_file: LICENSE
  summary: Geometry Understanding in Higher Dimensions
  description: |
    The GUDHI library is a generic open source C++ library, with a Python
    interface, for Topological Data Analysis (TDA) and Higher Dimensional
    Geometry Understanding. The library offers state-of-the-art data structures
    and algorithms to construct simplicial complexes and compute persistent
    homology.
  doc_url: http://gudhi.gforge.inria.fr/python/{{ version }}/
extra:
  recipe-maintainers:
    - VincentRouvreau
