{% set version = "3.0.0" %}
{% set commit = "de8e4aba94a0d5ecf933ad3ee1c05ccb866288b0" %}
{% set sha256 = "0f8e081b1400b1f04cf0228d8915bb3e9cc5e913ececb7206e258cbfbda89a2f" %}

package:
  name: gudhi
  version: {{ version }}

source:
  url: https://github.com/GUDHI/gudhi-devel/archive/{{ commit }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # C++11 only supports vc14
  skip: true  # [win and py2k]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - cython
    - boost-cpp {{ boost_version }}
    - eigen
    - cgal-cpp 4.14
  run:
    - python
    - numpy
    - boost-cpp {{ boost_version }}
    - cgal-cpp 4.14

test:
  commands:
    - test -f ${PREFIX}/include/gudhi/Simplex_tree.h  # [unix]
    - if not exist %LIBRARY_INC%\gudhi\Simplex_tree.h exit 1  # [win]
    - conda inspect linkages $PKG_NAME  # [not win]
    - conda inspect objects $PKG_NAME  # [osx]
    - python -c "import gudhi; diag1 = [[2.7, 3.7], [9.6, 14.0], [34.2, 34.974], [3.0, float('Inf')]]; diag2 = [[2.8, 4.45], [9.5, 14.1], [3.2, float('Inf')]]; assert gudhi.bottleneck_distance(diag1, diag2) == 0.75"
about:
  home: http://gudhi.gforge.inria.fr/
  license: MIT/GPL3
  license_file: LICENSE
  summary: Geometry Understanding in Higher Dimensions
  description: |
    The GUDHI library is a generic open source C++ library, with a Python
    interface, for Topological Data Analysis (TDA) and Higher Dimensional
    Geometry Understanding. The library offers state-of-the-art data structures
    and algorithms to construct simplicial complexes and compute persistent
    homology.
  doc_url: http://gudhi.gforge.inria.fr/python/{{ version }}/
extra:
  recipe-maintainers:
    - VincentRouvreau
