{% set version = "3.3.0" %}

package:
  name: gudhi
  version: {{ version }}

source:
  git_url: https://github.com/GUDHI/gudhi-devel.git
  git_rev: tags/gudhi-release-{{ version }}
# faster when last commit is the version tag
#  git_depth: 1

build:
  number: 4
  # for windows, no python 2.X
  skip: true  # [win and py2k]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - git
    - python
    - numpy
    - setuptools
    - cython
    - pybind11
    - boost-cpp
    - eigen
    - cgal-cpp 5.1.1.*
  run:
    - python
    - numpy
    - setuptools
    - boost-cpp
    - cgal-cpp 5.1.1.*

test:
  requires:
    - pytest
    - python
  source_files:
    - src/python/test
  commands:
    - test -f ${PREFIX}/include/gudhi/Simplex_tree.h  # [unix]
    - if not exist %LIBRARY_INC%\gudhi\Simplex_tree.h exit 1  # [win]
    - pytest src/python/test/test_alpha_complex.py
    - pytest src/python/test/test_bottleneck_distance.py
    - pytest src/python/test/test_cubical_complex.py
    - pytest src/python/test/test_euclidean_witness_complex.py
    - pytest src/python/test/test_reader_utils.py
    - pytest src/python/test/test_rips_complex.py
    - pytest src/python/test/test_simplex_generators.py
    - pytest src/python/test/test_simplex_tree.py
    - pytest src/python/test/test_subsampling.py
    - pytest src/python/test/test_tangential_complex.py
    - pytest src/python/test/test_time_delay.py
    - pytest src/python/test/test_witness_complex.py
about:
  home: http://gudhi.gforge.inria.fr/
  license: MIT AND BSD-3-Clause AND MPL-2.0 AND LGPL-3.0-or-later AND GPL-3.0-or-later
  license_file: LICENSE
  summary: Geometry Understanding in Higher Dimensions
  description: |
    The GUDHI library is a generic open source C++ library, with a Python
    interface, for Topological Data Analysis (TDA) and Higher Dimensional
    Geometry Understanding. The library offers state-of-the-art data structures
    and algorithms to construct simplicial complexes and compute persistent
    homology.
  doc_url: http://gudhi.gforge.inria.fr/python/{{ version }}/
extra:
  recipe-maintainers:
    - VincentRouvreau
