{% set version = "3.11.0" %}

package:
  name: gudhi
  version: {{ version }}

source:
  git_url: https://github.com/GUDHI/gudhi-devel.git
  git_rev: tags/gudhi-release-{{ version }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python

about:
  home: https://gudhi.inria.fr/
  license: MIT AND BSD-3-Clause AND MPL-2.0 AND LGPL-3.0-or-later AND GPL-3.0-or-later
  license_file: LICENSE
  summary: Geometry Understanding in Higher Dimensions
  description: |
    The GUDHI library is a generic open source C++ library, with a Python
    interface, for Topological Data Analysis (TDA) and Higher Dimensional
    Geometry Understanding. The library offers state-of-the-art data structures
    and algorithms to construct simplicial complexes and compute persistent
    homology.
  doc_url: https://gudhi.inria.fr/python/{{ version }}/
extra:
  recipe-maintainers:
    - VincentRouvreau
