travis:
  secure:
    BINSTAR_TOKEN: tOaJTgJPiWaCyfckQeNNptpXYPhRIWEIPDSi30FhCtIMiFoKDMCSOgEjviAKAyRC7wTzKSHmudj+nsohoEIr+ZMABf9HjvCsL2b0ZfrKeaXdXSP61BMMXxnMvN16T2BvT4r+FJfpM2WQe5f6+2/ZyIrrWanH+j5CO+Ou3zbE8zowKmPSm1K6lJCaUok53wv/g7SMBCZ5wQquHnmSk7A1Q8UVoBbz2Pg8Wf1y3CqvRlTV8JpgECCuZovP7bmVxbAhawBbXrvOmLRT1gEXAxFnZE8yVzI7bhTj/geQdmY8pSIpV0R1jPllvlpdYoaE+36ptJ1crpnW/5kl2wY4u2t4zqBEG74AjaNwRKmTZdxdd7VFy+w65U0+COeiR/5+LSy+U/t/DFZip7qToUHkUGFcDUoE5inmNS3fr5XJaFFwnHjL6PQ0ayv46IB1QT226HODnFD5PQd+Q/6BWp8LpMYNFwllz7S3rfnDhH67tPT/zHn3gpKrBUoIYJ1vmWA50PD+A3PLRcvQkPCBR/ED2fILE5TqRChWlktabIy2rA12FzJUFdm6VF6curLciFtwUz5EziUlD6kBrIg5lFyUjuplyI1OwCDWr2/d+r9u83GO0CNJ8fAj6t8zCl9Ek0nXURG6C+3D+T+BW5DPxCqwI/RUUbl1LFBSTDcrOFWAr3LYRzk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
