conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  win: azure
  osx_arm64: default
test: native_and_emulated
workflow_settings:
  pagefile_size:
    - os: win
      value: 16
  build_workspace_dir:
    - provider: azure
      os: win
      value: C:\\bld\\
  tools_install_dir:
    - provider: azure
      os: win
      value: C:\Miniforge
