build_platform:
  osx_arm64: osx_64
provider:
  win: azure
  linux_aarch64: default
conda_forge_output_validation: true
test_on_native_only: true
github:
  branch_name: main
  tooling_branch_name: main
